session_output htax_regress.acoskuner500.22_11_26_17_14_06_3691 {
	session_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691";
	original_session_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691";
	top_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/..";
	vsof: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/htax_regress.vsof";
	chain_id: "0";
	runs_in_session: "30";
	total_runs_in_session: "30";
	session_start_time: "1669504446";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	parsed_vsif: "parsed_htax_regress.acoskuner500.22_11_26_17_14_06_3691.vsif";
	full_title: "htax_regress";
	owner: "acoskuner500";
	enable_session_recovery_vmgr: "FALSE";
	original_vsif: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
	name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691";
	pre_session_script: <text> echo "pre_session_script" </text>;
	session_status: "in_progress";
}

run 1 {
	full_title: "htax_regress/all_test/test1";
	original_test_path: "___all_test___test1";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST1</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_1";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test1__run_1";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "21@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 2 {
	full_title: "htax_regress/all_test/test2";
	original_test_path: "___all_test___test2";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST2</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_2";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test2__run_2";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "27@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 3 {
	full_title: "htax_regress/all_test/test3";
	original_test_path: "___all_test___test3";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST3</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_3";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test3__run_3";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "33@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 4 {
	full_title: "htax_regress/all_test/test4";
	original_test_path: "___all_test___test4";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST4</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_4";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test4__run_4";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "39@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 5 {
	full_title: "htax_regress/all_test/test5";
	original_test_path: "___all_test___test5";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST5</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_5";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test5__run_5";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "45@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 6 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_6";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test6__run_6";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 7 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_7";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test6__run_7";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 8 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_8";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test6__run_8";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 9 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_9";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test6__run_9";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 10 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_10";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test6__run_10";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 11 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_11";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test7__run_11";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 12 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_12";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test7__run_12";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 13 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_13";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test7__run_13";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 14 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_14";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test7__run_14";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 15 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_15";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test7__run_15";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 16 {
	full_title: "htax_regress/all_test/test8";
	original_test_path: "___all_test___test8";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=short_packet_test -define TEST8</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_16";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test8__run_16";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "67@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 17 {
	full_title: "htax_regress/all_test/test8";
	original_test_path: "___all_test___test8";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=short_packet_test -define TEST8</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_17";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test8__run_17";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "67@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 18 {
	full_title: "htax_regress/all_test/test8";
	original_test_path: "___all_test___test8";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=short_packet_test -define TEST8</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_18";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test8__run_18";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "67@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 19 {
	full_title: "htax_regress/all_test/test8";
	original_test_path: "___all_test___test8";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=short_packet_test -define TEST8</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_19";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test8__run_19";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "67@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 20 {
	full_title: "htax_regress/all_test/test8";
	original_test_path: "___all_test___test8";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=short_packet_test -define TEST8</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_20";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test8__run_20";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "67@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 21 {
	full_title: "htax_regress/all_test/test9";
	original_test_path: "___all_test___test9";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=medium_packet_test -define TEST9</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_21";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test9__run_21";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "73@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 22 {
	full_title: "htax_regress/all_test/test9";
	original_test_path: "___all_test___test9";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=medium_packet_test -define TEST9</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_22";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test9__run_22";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "73@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 23 {
	full_title: "htax_regress/all_test/test9";
	original_test_path: "___all_test___test9";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=medium_packet_test -define TEST9</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_23";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test9__run_23";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "73@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 24 {
	full_title: "htax_regress/all_test/test9";
	original_test_path: "___all_test___test9";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=medium_packet_test -define TEST9</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_24";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test9__run_24";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "73@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 25 {
	full_title: "htax_regress/all_test/test9";
	original_test_path: "___all_test___test9";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=medium_packet_test -define TEST9</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_25";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test9__run_25";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "73@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 26 {
	full_title: "htax_regress/all_test/test10";
	original_test_path: "___all_test___test10";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=long_packet_test -define TEST10</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_26";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test10__run_26";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "79@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 27 {
	full_title: "htax_regress/all_test/test10";
	original_test_path: "___all_test___test10";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=long_packet_test -define TEST10</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_27";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test10__run_27";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "79@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 28 {
	full_title: "htax_regress/all_test/test10";
	original_test_path: "___all_test___test10";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=long_packet_test -define TEST10</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_28";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test10__run_28";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "79@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 29 {
	full_title: "htax_regress/all_test/test10";
	original_test_path: "___all_test___test10";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=long_packet_test -define TEST10</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_29";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test10__run_29";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "79@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 30 {
	full_title: "htax_regress/all_test/test10";
	original_test_path: "___all_test___test10";
	seed: "random";
	sv_seed: "random";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=long_packet_test -define TEST10</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/all_test/run_30";
	drm_job_name: "htax_regress.acoskuner500.22_11_26_17_14_06_3691_htax_regress___all_test___test10__run_30";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_26_17_14_06_3691/chain_0/vm_brun.log";
	vsif: "79@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

