session_output htax_regress.acoskuner500.22_11_28_19_31_21_2162 {
	session_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162";
	original_session_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162";
	top_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/..";
	vsof: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/htax_regress.vsof";
	chain_id: "0";
	runs_in_session: "15";
	total_runs_in_session: "15";
	session_start_time: "1669685481";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	parsed_vsif: "parsed_htax_regress.acoskuner500.22_11_28_19_31_21_2162.vsif";
	full_title: "htax_regress";
	owner: "acoskuner500";
	enable_session_recovery_vmgr: "FALSE";
	original_vsif: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
	name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162";
	pre_session_script: <text> echo "pre_session_script" </text>;
	session_status: "in_progress";
}

run 1 {
	full_title: "htax_regress/all_test/test1";
	original_test_path: "___all_test___test1";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST1</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_1";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test1__run_1";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "21@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 2 {
	full_title: "htax_regress/all_test/test2";
	original_test_path: "___all_test___test2";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST2</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_2";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test2__run_2";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "27@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 3 {
	full_title: "htax_regress/all_test/test3";
	original_test_path: "___all_test___test3";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST3</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_3";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test3__run_3";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "33@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 4 {
	full_title: "htax_regress/all_test/test4";
	original_test_path: "___all_test___test4";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST4</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_4";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test4__run_4";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "39@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 5 {
	full_title: "htax_regress/all_test/test5";
	original_test_path: "___all_test___test5";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_random_test -define TEST5</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_5";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test5__run_5";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "45@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 6 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_6";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test6__run_6";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 7 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_7";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test6__run_7";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 8 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_8";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test6__run_8";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 9 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_9";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test6__run_9";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 10 {
	full_title: "htax_regress/all_test/test6";
	original_test_path: "___all_test___test6";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=multiport_sequential_random_test -define TEST6</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_10";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test6__run_10";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "51@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 11 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_11";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test7__run_11";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 12 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_12";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test7__run_12";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 13 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_13";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test7__run_13";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 14 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_14";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test7__run_14";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

run 15 {
	full_title: "htax_regress/all_test/test7";
	original_test_path: "___all_test___test7";
	seed: "random";
	sv_seed: "616";
	e_seed: "random";
	estimated_duration_vmgr: "13000000";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim ; irun -f run_vm.f +UVM_TESTNAME=simple_port_port_test -define TEST7</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	test_group_name: "all_test";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/all_test/run_15";
	drm_job_name: "htax_regress.acoskuner500.22_11_28_19_31_21_2162_htax_regress___all_test___test7__run_15";
	estimated_duration_vmgr: "13000000";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_19_31_21_2162/chain_0/vm_brun.log";
	vsif: "61@/home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/run_vm.vsif";
}

