#!/bin/bash

if [ $# -ne 0 ];then
 /bin/echo 'Error: No arguments are supported.'
 exit 1;
fi

if [ "$RR_WITH_ENV" = "1" ]; then
. `rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_10_28_44_0470/chain_0 --group_dir /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_10_28_44_0470/chain_0/all_test --run_id 16 --seed random --e_seed random --sv_seed 616  --sve_name 
else
`rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_10_28_44_0470/chain_0 --group_dir /home/grads/a/acoskuner500/csce616/lab10_regression/lab10/sim/regression/htax_regress.acoskuner500.22_11_28_10_28_44_0470/chain_0/all_test --run_id 16 --seed random --e_seed random --sv_seed 616  --sve_name 
fi

